// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7x1p75Tk3hVAGJfxONNeCe68O5xAs-wM',
    appId: '1:443327720262:web:db0f80f3a6ced206969347',
    messagingSenderId: '443327720262',
    projectId: 'moviesapp-14f0a',
    authDomain: 'moviesapp-14f0a.firebaseapp.com',
    storageBucket: 'moviesapp-14f0a.appspot.com',
    measurementId: 'G-5JBDQKJRJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLLePOzBKQnhIVorltMFdVUc86HdDT08w',
    appId: '1:443327720262:android:4ffba9bb1b9c72a6969347',
    messagingSenderId: '443327720262',
    projectId: 'moviesapp-14f0a',
    storageBucket: 'moviesapp-14f0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz59IPMdMS4AIw27t4S6jnHKMp8Vuu-60',
    appId: '1:443327720262:ios:97a2fa6f670871a5969347',
    messagingSenderId: '443327720262',
    projectId: 'moviesapp-14f0a',
    storageBucket: 'moviesapp-14f0a.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
